import React, { useState } from 'react';
import { ActivityIndicator, Image, KeyboardAvoidingView, Linking as NativeLinking, Modal, Platform, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import type { DriverController } from './useDriver';
import type { Load } from './types';
import { loadPresentation, locationReady, updateAge } from './driver-state';

const colors = { ink: '#202c3d', muted: '#68788b', blue: '#286bc0', line: '#e4eaf1', soft: '#f5f8fc', green: '#267555', amber: '#936622' };
const date = (value: string) => new Date(value).toLocaleString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' });
function Button({ title, onPress, disabled = false, secondary = false, danger = false, testID }: { title: string; onPress: () => void; disabled?: boolean; secondary?: boolean; danger?: boolean; testID?: string }) {
  return <Pressable testID={testID} accessibilityRole="button" disabled={disabled} onPress={onPress} style={({ pressed }) => [s.button, secondary && s.secondary, danger && s.danger, (disabled || pressed) && s.dim]}><Text style={[s.buttonText, secondary && s.secondaryText, danger && s.dangerText]}>{title}</Text></Pressable>;
}
function Sheet({ visible, title, close, children }: { visible: boolean; title: string; close: () => void; children: React.ReactNode }) {
  const insets = useSafeAreaInsets();
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={close}><View style={s.sheetBackdrop}><Pressable accessibilityLabel="Close panel" onPress={close} style={StyleSheet.absoluteFill}/><View style={[s.sheet, { paddingBottom: Math.max(20, insets.bottom) }]}><View style={s.sheetHandle}/><View style={s.sheetHeading}><Text style={s.sheetTitle}>{title}</Text><Pressable accessibilityRole="button" accessibilityLabel="Close panel" onPress={close} style={s.close}><Text style={s.closeText}>×</Text></Pressable></View>{children}</View></View></Modal>;
}
function NavIcon({ name, active }: { name: 'loads' | 'history' | 'profile'; active: boolean }) {
  const color = active ? colors.blue : colors.muted;
  if (name === 'loads') return <View style={[s.navGlyph, { borderColor: color }]}><View style={[s.navGlyphLine, { backgroundColor: color }]}/><View style={[s.navGlyphLine, { backgroundColor: color }]}/></View>;
  if (name === 'history') return <View style={[s.navClock, { borderColor: color }]}><View style={[s.clockHand, { backgroundColor: color }]}/><View style={[s.clockMinute, { backgroundColor: color }]}/></View>;
  return <View style={s.navProfile}><View style={[s.profileHead, { borderColor: color }]}/><View style={[s.profileShoulders, { borderColor: color }]}/></View>;
}
function Route({ load, full = false }: { load: Load; full?: boolean }) {
  return <View style={s.route}><View style={s.routeRail}><View style={s.pickupDot}/><View style={s.routeLine}/><View style={s.deliveryDot}/></View><View style={s.routeCopy}><View><Text style={s.smallLabel}>PICKUP</Text><Text numberOfLines={full ? undefined : 2} style={s.address}>{load.pickupAddress || 'Not specified'}</Text></View><View><Text style={s.smallLabel}>DELIVERY</Text><Text numberOfLines={full ? undefined : 2} style={s.address}>{load.deliveryAddress || 'Not specified'}</Text></View></View></View>;
}
function PickupFiles({load,driver:d}: {load:Load;driver:DriverController}) {
  const state=load.pickupDocuments;
  if(!state?.documents.length)return null;
  const ended=['completed','cancelled','declined','expired'].includes(load.status) || state.status==='closed';
  const available=state.canOpen && !ended;
  return <View style={s.pickupFiles} testID={`pickup-documents-${load.id}`}><View style={s.pickupHeading}><Text style={s.label}>Pickup documents</Text><Text style={[s.pickupStatus,available?s.green:s.muted]}>{ended?'Closed':available?'Ready':'Locked'}</Text></View>
    {!available && !ended && <Text style={s.helper}>{state.status==='available'?'Accept the load to open your documents.':'Available within 1 mile of pickup.'}</Text>}
    {state.documents.map(file=><Pressable key={file.id} testID={`pickup-document-${file.id}`} accessibilityRole="button" accessibilityLabel={`${available?'Open':'Locked'} ${file.kind==='gate_pass'?'gate pass':'release form'}: ${file.name}`} disabled={!available || d.busy} onPress={()=>void d.openDocument(load,file.id)} style={s.pickupFile}><View style={s.pickupFileIcon}><Text style={s.pickupFileGlyph}>{available?'↗':'•'}</Text></View><View style={s.flex}><Text numberOfLines={2} style={s.pickupFileName}>{file.name}</Text><Text style={s.pickupFileType}>{file.kind==='gate_pass'?'Gate pass':'Release form'}</Text></View><Text style={[s.pickupFileAction,available?s.blue:s.muted]}>{available?'Open':ended?'Closed':'Locked'}</Text></Pressable>)}
    {!available && !ended && load.status==='active' && <Pressable accessibilityRole="button" disabled={d.busy} onPress={()=>void d.refreshPickupLocation()} style={s.pickupRefresh}><Text style={s.textLink}>{d.busy?'Please wait…':'Update location'}</Text></Pressable>}
  </View>;
}
export function DriverScreen({ driver: d }: { driver: DriverController }) {
  const [menu, setMenu] = useState<Load | null>(null), [detailId, setDetailId] = useState<string | null>(null);
  const detail=d.session ? d.loads.find(load=>load.id===detailId) || null : null;
  const setDetail=(load:Load|null)=>setDetailId(load?.id || null);
  const insets = useSafeAreaInsets();
  const active = d.loads.filter(load => load.status === 'active'), invitations = d.loads.filter(load => load.status === 'pending');
  const live = d.health.enabled && locationReady(d.access) && !d.health.error && d.health.queued === 0 && d.health.lastCapture && d.now - Date.parse(d.health.lastCapture) < 300000;
  const title = d.screen === 'history' ? 'History' : d.screen === 'profile' ? 'Profile' : 'Loads';
  const closeMenu = () => { if (!d.busy) setMenu(null); };
  const permissionTitle = !d.permissionForLoad && d.access.services ? 'Location access' : !d.access.services ? 'Turn on location services' : d.permissionStep === 'settings' ? 'Choose Always in Settings' : 'Enable location for your load';
  const permissionIntro = Platform.OS === 'ios' ? 'Choose Always so updates continue with your screen locked.' : 'Allow location all the time so updates continue with your screen locked.';
  if (d.booting) return <SafeAreaView style={s.root}><ActivityIndicator color={colors.blue} style={s.boot}/></SafeAreaView>;
  return <SafeAreaView edges={['top']} style={s.root}>
    <View style={s.header}><View style={s.brand}><Image source={require('../assets/shield-mark.png')} style={s.logo}/><Text style={s.brandName}>DeepTruck <Text style={s.brandSuffix}>Driver</Text></Text></View>{d.session && <Pressable testID="profile-shortcut" accessibilityRole="button" accessibilityLabel="Open profile" onPress={() => d.setScreen('profile')} style={s.avatar}><NavIcon name="profile" active={d.screen === 'profile'}/></Pressable>}</View>
    {!d.session ? <KeyboardAvoidingView style={s.flex} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.login}>
      <Text style={s.loginTitle}>{d.codeSent ? 'Enter your code' : 'Sign in to view your loads'}</Text><Text style={s.loginCaption}>{d.codeSent ? `Sent to ${d.number}` : 'Use the number that received your invitation.'}</Text>
      <View style={s.loginForm}><Text style={s.label}>{d.codeSent ? 'SMS code' : 'Phone number'}</Text>{d.codeSent ? <TextInput accessibilityLabel="SMS code" style={s.input} value={d.otp} onChangeText={value => d.setOtp(value.replace(/\D/g, ''))} keyboardType="number-pad" textContentType="oneTimeCode" autoComplete="sms-otp" maxLength={6} editable={!d.busy} placeholder="000000"/> : <TextInput accessibilityLabel="Phone number" style={s.input} value={d.number} onChangeText={d.setNumber} keyboardType="phone-pad" textContentType="telephoneNumber" placeholder="+1 (555) 123-4567" editable={!d.busy}/>}
        <Button testID="login-submit" title={d.busy ? 'Please wait…' : d.codeSent ? 'Continue' : 'Send code'} disabled={d.busy || (d.codeSent ? d.otp.length !== 6 : !d.number.trim() || d.now < d.nextSmsAt)} onPress={() => void (d.codeSent ? d.verifyCode() : d.sendCode())}/>
        {d.codeSent && <View style={s.loginLinks}><Pressable accessibilityRole="button" disabled={d.busy || d.now < d.nextSmsAt} onPress={() => void d.sendCode()}><Text style={[s.textLink, d.now < d.nextSmsAt && s.muted]}>{d.now < d.nextSmsAt ? `Resend in ${Math.ceil((d.nextSmsAt - d.now) / 1000)}s` : 'Resend code'}</Text></Pressable><Pressable accessibilityRole="button" disabled={d.busy} onPress={d.changeNumber}><Text style={s.textLink}>Change number</Text></Pressable></View>}
      </View>{d.message ? <Text accessibilityLiveRegion="polite" style={s.error}>{d.message}</Text> : null}
    </ScrollView></KeyboardAvoidingView> : <>
      <ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={d.refreshing} onRefresh={() => void d.refresh()} tintColor={colors.blue}/>}>
        <View style={s.pageHeading}><Text style={s.title}>{title}</Text>{d.screen === 'loads' && invitations.length > 0 && <Text style={s.newCount}>{invitations.length} new</Text>}</View>
        {d.screen !== 'profile' && active.length > 0 && <View style={s.trackingStrip}><View style={[s.statusDot, { backgroundColor: live ? colors.green : colors.amber }]}/><Text style={s.stripText}>{live ? `${active.length} load${active.length === 1 ? '' : 's'} tracking` : loadPresentation(active[0], d.health, d.access, d.now).label}</Text>{active.length > 1 && <Pressable accessibilityRole="button" disabled={d.busy} onPress={() => void d.stopAll()}><Text style={s.textLink}>Pause all</Text></Pressable>}</View>}
        {d.message ? <View style={s.notice}><Text accessibilityLiveRegion="polite" style={s.noticeText}>{d.message}</Text><Pressable accessibilityRole="button" accessibilityLabel="Dismiss message" onPress={d.dismissMessage}><Text style={s.noticeClose}>×</Text></Pressable></View> : null}
        {d.screen === 'profile' ? <>
          <View style={s.account}><View style={s.accountAvatar}><NavIcon name="profile" active/></View><View><Text style={s.accountPhone}>{d.session.user.phone ? '+' + d.session.user.phone.replace(/^\+/, '') : 'Your account'}</Text><Text style={s.accountVerified}>Verified phone number</Text></View></View>
          <View style={s.settingsGroup}><Text style={s.groupTitle}>Location</Text>{[['Location services', d.access.services ? 'On' : 'Off'], ['Background access', d.access.background ? Platform.OS === 'ios' ? 'Always' : 'Allowed' : 'Required'], ['Accuracy', d.access.precise ? 'Precise' : 'Approximate']].map(([label, value]) => <View style={s.settingRow} key={label}><Text style={s.settingLabel}>{label}</Text><Text style={[s.settingValue, value === 'Required' || value === 'Off' ? s.amber : s.muted]}>{value}</Text></View>)}<Button title={locationReady(d.access) ? "Open location settings" : "Configure location"} secondary disabled={d.busy} onPress={() => void (locationReady(d.access) ? d.openProfileSettings() : d.showPermissions())}/><Text style={s.helper}>Permission alone does not start tracking.</Text></View>
          {active.length > 0 && <Button title="Pause all tracking" secondary danger disabled={d.busy} onPress={() => void d.stopAll()}/>}
          <View style={s.profileLinks}><Pressable accessibilityRole="link" onPress={() => void NativeLinking.openURL('https://www.deeptruck.io/help/accept-load')}><Text style={s.textLink}>Help Center ↗</Text></Pressable><Pressable accessibilityRole="link" onPress={() => void NativeLinking.openURL('https://www.deeptruck.io/privacy')}><Text style={s.textLink}>Privacy policy ↗</Text></Pressable><Pressable accessibilityRole="button" disabled={d.busy} onPress={() => void d.stopAll(true)}><Text style={s.signOut}>Sign out</Text></Pressable></View>
        </> : <>
          {d.loadError ? <Text accessibilityLiveRegion="polite" style={s.error}>{d.loadError}</Text> : null}
          {!d.visible.length ? <View style={s.empty}><Text style={s.emptyTitle}>{!d.loadsLoaded ? d.loadError ? 'Unable to load your invitations' : 'Loading your loads…' : d.screen === 'history' ? 'No past loads' : 'No loads yet'}</Text>{!d.loadsLoaded ? d.loadError ? <Button title="Try again" secondary onPress={() => void d.refresh()} disabled={d.refreshing || d.busy}/> : <ActivityIndicator color={colors.blue}/> : <Text style={s.emptyCopy}>{d.screen === 'history' ? 'Completed deliveries appear here.' : 'Invitations to your phone number appear here.'}</Text>}</View> : d.visible.map(load => {
            const state = loadPresentation(load, d.health, d.access, d.now);
            const pausedAction = state.action === 'Pause tracking';
            return <View key={load.id} testID={`load-card-${load.id}`} style={[s.card, load.id === d.invite && s.invited]}>
              <View style={s.cardTop}><Text numberOfLines={1} style={s.dealer}>{load.dealerName}</Text><View style={[s.badge, state.tone === 'green' ? s.badgeGreen : state.tone === 'amber' ? s.badgeAmber : state.tone === 'blue' ? s.badgeBlue : null]}><Text style={[s.badgeText, state.tone === 'green' ? s.green : state.tone === 'amber' ? s.amber : state.tone === 'blue' ? s.blue : null]}>{state.label}</Text></View></View>
              <Pressable accessibilityRole="button" accessibilityLabel={`View details for ${load.title}`} onPress={() => setDetail(load)}><Text style={s.loadTitle}>{load.title}</Text><Route load={load}/></Pressable>
              <PickupFiles load={load} driver={d}/>
              <View style={s.cardMeta}><Text style={s.metaText}>{load.status === 'active' && d.health.enabled ? updateAge(d.health.lastUpload, d.now) : `Access until ${date(load.expiresAt)}`}</Text><Pressable accessibilityRole="button" accessibilityLabel={`More actions for ${load.title}`} disabled={d.busy} onPress={() => setMenu(load)} style={s.more}><Text style={s.moreText}>•••</Text></Pressable></View>
              {state.action && <Button testID={`load-primary-${load.id}`} title={d.busy ? 'Please wait…' : state.action} secondary={pausedAction} disabled={d.busy} onPress={() => void (pausedAction ? d.act(load, 'pause') : d.beginStart(load))}/>}
              {['pending', 'accepted'].includes(load.status) && <Text style={s.consent}>Shares location with {load.dealerName} until {date(load.expiresAt)}. Pause anytime.</Text>}
              {['accepted', 'active', 'paused'].includes(load.status) && <Pressable testID={`load-complete-${load.id}`} accessibilityRole="button" disabled={d.busy} onPress={() => void d.act(load, 'complete')} style={s.complete}><Text style={s.completeText}>Complete delivery</Text></Pressable>}
            </View>;
          })}
        </>}
      </ScrollView>
      <View style={[s.navigation, { paddingBottom: Math.max(8, insets.bottom) }]}>{(['loads', 'history', 'profile'] as const).map(name => <Pressable testID={`nav-${name}`} key={name} accessibilityRole="tab" accessibilityState={{ selected: d.screen === name }} onPress={() => d.setScreen(name)} style={s.navItem}><NavIcon name={name} active={d.screen === name}/><Text style={[s.navLabel, d.screen === name && s.blue]}>{name === 'loads' ? 'Loads' : name === 'history' ? 'History' : 'Profile'}</Text></Pressable>)}</View>
    </>}
    <Sheet visible={d.permissionOpen} title={permissionTitle} close={d.closePermission}>
      <Text style={s.sheetCopy}>{!d.access.services ? 'Turn on Location Services, then allow background access for DeepTruck Driver.' : permissionIntro}</Text>
      <View style={s.permissionSteps}>{(!d.access.services ? [[1, 'Privacy & Security → Location Services'], [2, 'Turn on Location Services']] : d.permissionStep === 'settings' ? [[1, Platform.OS === 'ios' ? 'DeepTruck Driver → Location' : 'App permissions → Location'], [2, Platform.OS === 'ios' ? 'Select Always' : 'Select Allow all the time']] : [[1, Platform.OS === 'ios' ? 'Allow While Using the App' : 'Allow location access'], [2, Platform.OS === 'ios' ? 'Then choose Always' : 'Then allow all the time']]).map(([number, label]) => <View key={number} style={s.permissionRow}><View style={s.permissionNumber}><Text style={s.permissionNumberText}>{number}</Text></View><Text style={s.permissionLabel}>{label}</Text></View>)}</View>
      <Text style={s.helper}>Location is shared only for loads you start. You can pause anytime.</Text>
      {d.message ? <Text style={s.error}>{d.message}</Text> : null}
      <Button testID="permission-continue" title={d.busy ? 'Please wait…' : d.permissionStep === 'settings' || !d.access.services ? 'Open settings' : 'Enable location'} disabled={d.busy} onPress={() => void (d.permissionStep === 'settings' || !d.access.services ? d.openSettings() : d.enableLocation())}/>
    </Sheet>
    <Sheet visible={Boolean(menu)} title={menu?.title || 'Load actions'} close={closeMenu}>{menu && <View style={s.sheetActions}><Button title="View details" secondary onPress={() => { setDetail(menu); setMenu(null); }}/>{menu.status === 'pending' && <><Button testID="accept-later" title="Accept, start later" secondary disabled={d.busy} onPress={() => { void d.act(menu, 'accept'); setMenu(null); }}/><Button title="Decline invitation" secondary danger disabled={d.busy} onPress={() => { void d.act(menu, 'decline'); setMenu(null); }}/></>}</View>}</Sheet>
    <Sheet visible={Boolean(detail)} title="Load details" close={() => setDetail(null)}>{detail && <ScrollView style={s.detailScroll}><Text style={s.loadTitle}>{detail.title}</Text><Text style={s.detailCarrier}>{detail.carrierName} · USDOT {detail.carrierDot}</Text><Route load={detail} full/><PickupFiles load={detail} driver={d}/>{d.message?<Text accessibilityLiveRegion="polite" style={s.error}>{d.message}</Text>:null}<View style={s.detailsGroup}><Text style={s.label}>Vehicles</Text>{detail.vehicles.length ? detail.vehicles.map((vehicle, index) => <Text key={index} style={s.detailValue}>{vehicle}</Text>) : <Text style={s.detailValue}>Not specified</Text>}</View>{detail.plannedAt && <View style={s.detailsGroup}><Text style={s.label}>Planned pickup</Text><Text style={s.detailValue}>{date(detail.plannedAt)}</Text></View>}<View style={s.detailsGroup}><Text style={s.label}>Location access ends</Text><Text style={s.detailValue}>{date(detail.expiresAt)}</Text></View></ScrollView>}</Sheet>
  </SafeAreaView>;
}
const s = StyleSheet.create({
  pickupFiles: { borderTopWidth: 1, borderTopColor: colors.line, paddingTop: 12, gap: 7 }, pickupHeading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 }, pickupStatus: { fontSize: 10, fontWeight: '500' }, pickupFile: { flexDirection: 'row', alignItems: 'center', gap: 10, minHeight: 54, paddingVertical: 7 }, pickupFileIcon: { width: 29, height: 34, borderRadius: 5, backgroundColor: colors.soft, alignItems: 'center', justifyContent: 'center' }, pickupFileGlyph: { color: colors.blue, fontSize: 17 }, pickupFileName: { color: colors.ink, fontSize: 12, lineHeight: 17, fontWeight: '500' }, pickupFileType: { color: colors.muted, fontSize: 10, marginTop: 3 }, pickupFileAction: { fontSize: 11, fontWeight: '500' }, pickupRefresh: { minHeight: 34, alignSelf: 'flex-start', justifyContent: 'center' },
  root: { flex: 1, backgroundColor: '#fff' }, flex: { flex: 1 }, boot: { flex: 1 }, header: { height: 64, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.line }, brand: { flexDirection: 'row', alignItems: 'center', gap: 8 }, logo: { width: 26, height: 30 }, brandName: { color: colors.ink, fontSize: 19, fontWeight: '600', letterSpacing: -.5 }, brandSuffix: { color: colors.muted, fontSize: 13, fontWeight: '400', letterSpacing: 0 }, avatar: { height: 36, width: 36, borderRadius: 18, backgroundColor: colors.soft, alignItems: 'center', justifyContent: 'center' },
  content: { paddingHorizontal: 20, paddingTop: 22, paddingBottom: 24, gap: 16 }, pageHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 2 }, title: { fontSize: 26, fontWeight: '600', color: colors.ink, letterSpacing: -.8 }, newCount: { fontSize: 12, fontWeight: '500', color: colors.blue, backgroundColor: '#edf4ff', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 6 }, trackingStrip: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingBottom: 2 }, stripText: { flex: 1, color: colors.muted, fontSize: 12 }, statusDot: { width: 6, height: 6, borderRadius: 3 },
  card: { padding: 16, borderWidth: 1, borderColor: colors.line, borderRadius: 12, backgroundColor: '#fff', gap: 12 }, invited: { borderColor: '#b9d0ec' }, cardTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 }, dealer: { flex: 1, fontSize: 12, fontWeight: '500', color: colors.muted }, badge: { paddingHorizontal: 7, paddingVertical: 5, borderRadius: 5, backgroundColor: colors.soft }, badgeGreen: { backgroundColor: '#ecf7f0' }, badgeAmber: { backgroundColor: '#fff5e4' }, badgeBlue: { backgroundColor: '#edf4ff' }, badgeText: { color: colors.muted, fontSize: 10, fontWeight: '500' }, loadTitle: { color: colors.ink, fontSize: 19, fontWeight: '600', lineHeight: 25, letterSpacing: -.3 }, route: { flexDirection: 'row', gap: 12, paddingTop: 17 }, routeRail: { width: 12, alignItems: 'center', paddingTop: 6, paddingBottom: 11 }, pickupDot: { height: 7, width: 7, borderRadius: 4, borderWidth: 1.5, borderColor: '#99acc3' }, routeLine: { flex: 1, minHeight: 33, width: 1, backgroundColor: colors.line, marginVertical: 5 }, deliveryDot: { height: 7, width: 7, borderRadius: 2, backgroundColor: colors.blue }, routeCopy: { flex: 1, gap: 13 }, smallLabel: { fontSize: 9, fontWeight: '500', color: colors.muted, letterSpacing: .6, marginBottom: 4 }, address: { color: colors.ink, fontSize: 13, lineHeight: 18 }, cardMeta: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, marginTop: 2 }, metaText: { color: colors.muted, fontSize: 11, flex: 1 }, more: { minWidth: 36, height: 32, alignItems: 'center', justifyContent: 'center' }, moreText: { color: colors.muted, fontSize: 14, letterSpacing: 1 }, consent: { fontSize: 10, lineHeight: 15, color: colors.muted }, complete: { minHeight: 34, alignItems: 'center', justifyContent: 'center' }, completeText: { fontSize: 12, color: colors.muted, fontWeight: '500' },
  button: { minHeight: 46, borderRadius: 8, backgroundColor: colors.blue, paddingVertical: 12, paddingHorizontal: 16, alignItems: 'center', justifyContent: 'center' }, buttonText: { color: '#fff', fontSize: 13, fontWeight: '600' }, secondary: { backgroundColor: colors.soft, borderWidth: 1, borderColor: colors.line }, secondaryText: { color: colors.ink }, danger: { backgroundColor: '#fff6f5', borderColor: '#f0dedb' }, dangerText: { color: '#a24337' }, dim: { opacity: .5 }, blue: { color: colors.blue }, muted: { color: colors.muted }, green: { color: colors.green }, amber: { color: colors.amber }, label: { fontSize: 12, color: colors.muted, fontWeight: '500' }, textLink: { fontSize: 12, color: colors.blue, fontWeight: '500' }, helper: { fontSize: 11, lineHeight: 17, color: colors.muted },
  navigation: { borderTopWidth: 1, borderTopColor: colors.line, backgroundColor: '#fff', paddingTop: 11, flexDirection: 'row' }, navItem: { flex: 1, minHeight: 46, alignItems: 'center', gap: 7 }, navLabel: { fontSize: 10, fontWeight: '500', color: colors.muted }, navGlyph: { width: 18, height: 19, borderWidth: 1.4, borderRadius: 3, paddingHorizontal: 3, justifyContent: 'center', gap: 4 }, navGlyphLine: { height: 1.4, width: 9 }, navClock: { width: 19, height: 19, borderWidth: 1.4, borderRadius: 10 }, clockHand: { position: 'absolute', left: 8, top: 3, width: 1.4, height: 6 }, clockMinute: { position: 'absolute', left: 8, top: 8, height: 1.4, width: 5 }, navProfile: { height: 19, width: 19, alignItems: 'center', justifyContent: 'space-between' }, profileHead: { height: 8, width: 8, borderWidth: 1.4, borderRadius: 5 }, profileShoulders: { width: 17, height: 8, borderWidth: 1.4, borderTopLeftRadius: 8, borderTopRightRadius: 8, borderBottomWidth: 0 },
  login: { padding: 24, paddingTop: 40, gap: 14 }, loginTitle: { fontSize: 27, lineHeight: 34, fontWeight: '600', color: colors.ink, letterSpacing: -.7 }, loginCaption: { color: colors.muted, fontSize: 13, lineHeight: 20 }, loginForm: { gap: 12, paddingTop: 17 }, input: { borderColor: '#cfdae7', borderWidth: 1, borderRadius: 8, minHeight: 50, paddingHorizontal: 14, fontSize: 17, color: colors.ink, backgroundColor: '#fff' }, loginLinks: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingTop: 6 }, error: { fontSize: 12, lineHeight: 19, color: '#a54535', backgroundColor: '#fff3ef', padding: 12, borderRadius: 8 }, notice: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#fff6e7', padding: 12, borderRadius: 8 }, noticeText: { flex: 1, color: '#856221', fontSize: 12, lineHeight: 18 }, noticeClose: { color: '#856221', fontSize: 23 }, empty: { paddingVertical: 38, gap: 14, alignItems: 'center' }, emptyTitle: { color: colors.ink, fontSize: 16, fontWeight: '500' }, emptyCopy: { color: colors.muted, fontSize: 12, lineHeight: 19, textAlign: 'center' },
  account: { flexDirection: 'row', alignItems: 'center', gap: 14, paddingVertical: 5 }, accountAvatar: { height: 48, width: 48, borderRadius: 24, backgroundColor: colors.soft, alignItems: 'center', justifyContent: 'center' }, accountPhone: { color: colors.ink, fontSize: 17, fontWeight: '500' }, accountVerified: { color: colors.muted, fontSize: 11, marginTop: 5 }, settingsGroup: { borderColor: colors.line, borderWidth: 1, borderRadius: 12, padding: 16, gap: 16, marginTop: 4 }, groupTitle: { color: colors.ink, fontSize: 15, fontWeight: '600' }, settingRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 }, settingLabel: { color: colors.ink, fontSize: 13 }, settingValue: { fontSize: 12, fontWeight: '500' }, profileLinks: { gap: 28, paddingVertical: 14, alignItems: 'flex-start' }, signOut: { color: '#a24337', fontSize: 13, fontWeight: '500' },
  sheetBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: '#14223666' }, sheet: { backgroundColor: '#fff', borderTopLeftRadius: 22, borderTopRightRadius: 22, padding: 24, paddingTop: 12, gap: 18, maxHeight: '85%' }, sheetHandle: { height: 4, width: 32, backgroundColor: '#d5dce5', borderRadius: 3, alignSelf: 'center', marginBottom: 3 }, sheetHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 }, sheetTitle: { flex: 1, color: colors.ink, fontSize: 21, lineHeight: 27, fontWeight: '600', letterSpacing: -.4 }, close: { height: 32, width: 32, borderRadius: 16, backgroundColor: colors.soft, alignItems: 'center', justifyContent: 'center' }, closeText: { color: colors.muted, fontSize: 25, lineHeight: 27 }, sheetCopy: { color: colors.muted, fontSize: 13, lineHeight: 20 }, permissionSteps: { backgroundColor: colors.soft, borderRadius: 10, padding: 16, gap: 18 }, permissionRow: { flexDirection: 'row', alignItems: 'center', gap: 12 }, permissionNumber: { backgroundColor: '#e5eefb', height: 26, width: 26, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, permissionNumberText: { color: colors.blue, fontSize: 12, fontWeight: '600' }, permissionLabel: { flex: 1, color: colors.ink, fontSize: 13, lineHeight: 19 }, sheetActions: { gap: 12 }, detailScroll: { flexGrow: 0 }, detailCarrier: { color: colors.muted, fontSize: 12, lineHeight: 19, marginTop: 8 }, detailsGroup: { gap: 7, paddingTop: 22, paddingBottom: 4 }, detailValue: { color: colors.ink, fontSize: 13, lineHeight: 19 }
});
