import React,{useState} from 'react';
import {ActivityIndicator,Alert,Image,Modal,Pressable,ScrollView,Share,StyleSheet,Text,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import * as Crypto from 'expo-crypto';
import {DAMAGE_AREAS,DAMAGE_SIZES,damageOptions,damageRecord,type DamageRecord,type VehicleView} from '../../supabase/functions/_shared/damage-codes';
import type {Load,PickupDocument} from './types';
import {VehicleDiagram} from './VehicleDiagram';
import {useInspection} from './useInspection';

export function InspectionScreen({actor,load,document,close,onFinished}:{actor:string;load:Load;document:PickupDocument;close:()=>void;onFinished:()=>void}){
  const i=useInspection(actor,load.id,document.id,onFinished),[view,setView]=useState<VehicleView>('left'),[area,setArea]=useState(''),[type,setType]=useState(''),[size,setSize]=useState<number|null>(null),[editing,setEditing]=useState<string|null>(null),[review,setReview]=useState(false),[noDamage,setNoDamage]=useState(false);
  const draft=i.draft,finished=draft?.status==='completed',options=damageOptions(area),chosen=options.find(t=>t.id===type),fixed=chosen&&'fixedSeverity' in chosen?chosen.fixedSeverity:null;
  function choosePart(id:string){setArea(id);setType('');setSize(null);setEditing(null);}
  function edit(d:DamageRecord){setView(DAMAGE_AREAS.find(a=>a.id===d.areaId)!.view);setArea(d.areaId);setType(d.typeId);setSize(d.severity);setEditing(d.id);setReview(false);}
  async function add(){if(!area||!type||!(fixed||size))return;const id=editing || Crypto.randomUUID(),isNew=!editing;await i.saveDamage(damageRecord({id,areaId:area,typeId:type,severity:fixed||size!}));setArea('');setEditing(null);setNoDamage(false);if(isNew)await i.addPhoto(id,true);}
  function remove(d:DamageRecord){Alert.alert('Remove damage?',d.areaLabel,[{text:'Keep',style:'cancel'},{text:'Remove',style:'destructive',onPress:()=>void i.removeDamage(d.id)}]);}
  function finish(){Alert.alert('Finish pickup inspection?',draft?.damages.length?`${draft.damages.length} damage note${draft.damages.length===1?'':'s'} will be written on this gate pass.`:'The gate pass will say “No visible damage observed by driver.”',[{text:'Review',style:'cancel'},{text:'Finish',onPress:()=>void i.publish(true,noDamage)}]);}
  return <Modal visible animationType="slide" onRequestClose={close}><SafeAreaView style={s.root}><View style={s.heading}><Pressable onPress={review&&!finished?()=>setReview(false):close} style={s.back} accessibilityRole="button"><Text style={s.link}>{review&&!finished?'‹ Back':'‹ Loads'}</Text></Pressable><Text style={s.title}>{finished?'Pickup inspection':review?'Review gate pass':'Record damage'}</Text></View>
    {i.loading?<ActivityIndicator style={s.loading} color="#286bc0"/>:<ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.content}>
      <View style={s.document}><Text style={s.label}>GATE PASS</Text><Text numberOfLines={2} style={s.file}>{document.name}</Text></View>
      {i.message?<View style={s.notice}><Text accessibilityLiveRegion="polite" style={s.noticeText}>{i.message}</Text>{draft&&!finished&&<Pressable onPress={()=>void i.sync().catch(()=>{})}><Text style={s.link}>Retry sync</Text></Pressable>}</View>:null}
      {!draft?<><Text style={s.helper}>Open an inspection to record pickup damage.</Text><Action title="Start inspection" disabled={i.busy} onPress={()=>void i.start()}/></>:<>
        <View style={s.status}><View style={[s.dot,{backgroundColor:finished?'#267555':i.syncing?'#936622':'#286bc0'}]}/><Text style={s.helper}>{finished?'Recorded on gate pass':i.syncing?'Syncing…':draft.sequence>draft.syncedSequence?'Saved on this phone':'Draft saved'}</Text><Text style={s.count}>{draft.damages.length} damage{draft.damages.length===1?'':'s'}</Text></View>
        {!review&&!finished&&<>{!area&&<VehicleDiagram view={view} onView={setView} selected={area} onSelect={choosePart} marked={draft.damages.map(d=>d.areaId)}/>} {area&&<View style={s.editor}><View style={s.recordTop}><Text style={[s.section,s.flex]}>{DAMAGE_AREAS.find(a=>a.id===area)!.label}</Text><Pressable style={s.smallAction} onPress={()=>setArea('')}><Text style={s.link}>Change part</Text></Pressable></View><Text style={s.label}>DAMAGE TYPE</Text><View style={s.options}>{options.map(t=><Choice key={t.id} label={t.label} selected={type===t.id} onPress={()=>{setType(t.id);setSize(null);}}/>)}</View>{chosen&&!fixed&&<><Text style={s.label}>SIZE AT THE LONGEST POINT</Text><View style={s.options}>{DAMAGE_SIZES.map(v=><Choice key={v.value} label={v.label} selected={size===v.value} onPress={()=>setSize(v.value)}/>)}</View></>}{chosen&&<Text style={s.helper}>Code {DAMAGE_AREAS.find(a=>a.id===area)!.code}-{chosen.code}-{fixed||size||'…'}</Text>}<Action title={editing?'Save change':'Add damage & take photo'} disabled={!chosen||!(fixed||size)||i.busy||(!editing&&draft.damages.length>=40)} onPress={()=>void add()}/></View>}</>}
        {(review||finished)&&<Text style={s.section}>{finished?'Recorded damages':'Codes on your gate pass'}</Text>}
        {draft.damages.map((d,index)=>{const photos=draft.photos.filter(p=>p.damageId===d.id);return <View key={d.id} style={s.record}><View style={s.recordTop}><View style={s.flex}><Text style={s.partName}>{index+1}. {d.areaLabel}</Text><Text style={s.helper}>{d.typeLabel} · {d.sizeLabel}</Text></View><Text selectable style={s.code}>{d.code}</Text></View><View style={s.photos}>{photos.map(p=><Pressable key={p.id} onPress={()=>p.uploaded&&void i.openPhoto(p.id)} accessibilityLabel="Open damage photo"><Image source={{uri:p.uri||p.url}} style={s.photo}/>{!p.uploaded&&<Text style={s.photoStatus}>On phone</Text>}</Pressable>)}</View>{!finished&&<View style={s.row}><Pressable disabled={i.busy||photos.length>=3} onPress={()=>void i.addPhoto(d.id,true)} style={s.smallAction}><Text style={s.link}>Take photo</Text></Pressable><Pressable disabled={i.busy||photos.length>=3} onPress={()=>void i.addPhoto(d.id,false)} style={s.smallAction}><Text style={s.link}>Choose photo</Text></Pressable><Pressable disabled={i.busy} onPress={()=>edit(d)} style={s.smallAction}><Text style={s.link}>Edit</Text></Pressable><Pressable disabled={i.busy} onPress={()=>remove(d)} style={s.smallAction}><Text style={s.remove}>×</Text></Pressable></View>}{!photos.length&&!finished&&<Text style={s.required}>Add at least one photo</Text>}</View>;})}
        {!draft.damages.length&&<Pressable disabled={finished} accessibilityRole="checkbox" accessibilityState={{checked:finished||noDamage}} onPress={()=>setNoDamage(!noDamage)} style={s.noDamage}><Text style={s.check}>{finished||noDamage?'☑':'□'}</Text><Text style={s.partName}>No visible damage observed</Text></Pressable>}
        {(review||finished)&&draft.damages.length>0&&<Pressable onPress={()=>void Share.share({message:draft.damages.map(d=>`${d.code}  ${d.areaLabel} — ${d.typeLabel}, ${d.sizeLabel}`).join('\n')})} style={s.smallAction}><Text style={s.link}>Share codes to copy</Text></Pressable>}
        {finished?<><Action title="Open annotated gate pass" onPress={()=>void i.openPdf()} disabled={i.busy}/>{draft.shareUrl&&<Action secondary title="Share damage photos" onPress={()=>void Share.share({message:draft.shareUrl!})}/>}<Text style={s.helper}>Open the PDF to share or print it.</Text></>:review?<><Action secondary title="Preview gate pass" onPress={()=>void i.publish(false,noDamage)} disabled={i.busy}/><Action title={i.busy?'Saving…':'Finish & save on gate pass'} onPress={finish} disabled={i.busy||(!draft.damages.length&&!noDamage)}/></>:<Action title="Review gate pass" disabled={i.busy||(!draft.damages.length&&!noDamage)} onPress={()=>{setReview(true);setArea('');}}/>}
      </>}
    </ScrollView>}
  </SafeAreaView></Modal>;
}
function Action({title,onPress,disabled=false,secondary=false}:{title:string;onPress:()=>void;disabled?:boolean;secondary?:boolean}){return <Pressable accessibilityRole="button" onPress={onPress} disabled={disabled} style={[s.button,secondary&&s.secondary,disabled&&s.dim]}><Text style={[s.buttonText,secondary&&s.secondaryText]}>{title}</Text></Pressable>;}
function Choice({label,onPress,selected}:{label:string;onPress:()=>void;selected:boolean}){return <Pressable accessibilityRole="button" accessibilityState={{selected}} onPress={onPress} style={[s.choice,selected&&s.chosen]}><Text style={[s.choiceText,selected&&s.link]}>{label}</Text></Pressable>;}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#fff'},loading:{flex:1},heading:{paddingHorizontal:20,paddingVertical:14,borderBottomWidth:1,borderBottomColor:'#e4eaf1',gap:15},back:{alignSelf:'flex-start',minHeight:30,justifyContent:'center'},title:{fontSize:23,fontWeight:'600',color:'#202c3d',letterSpacing:-.5},content:{padding:20,gap:17,paddingBottom:35},document:{gap:5},label:{fontSize:10,fontWeight:'500',letterSpacing:.6,color:'#68788b'},file:{fontSize:12,color:'#68788b'},section:{fontSize:17,color:'#202c3d',fontWeight:'600'},helper:{fontSize:11,color:'#68788b',lineHeight:17},status:{flexDirection:'row',alignItems:'center',gap:7},dot:{width:6,height:6,borderRadius:3},count:{marginLeft:'auto',fontSize:11,color:'#68788b'},editor:{gap:14,padding:15,borderWidth:1,borderColor:'#e4eaf1',borderRadius:10},options:{flexDirection:'row',flexWrap:'wrap',gap:7},choice:{borderWidth:1,borderColor:'#e4eaf1',paddingHorizontal:11,paddingVertical:12,borderRadius:7},chosen:{borderColor:'#85b4eb',backgroundColor:'#edf4ff'},choiceText:{fontSize:12,color:'#202c3d'},record:{gap:12,borderTopWidth:1,borderTopColor:'#e4eaf1',paddingTop:16},recordTop:{flexDirection:'row',gap:12,alignItems:'flex-start'},flex:{flex:1,gap:5},partName:{fontSize:13,fontWeight:'500',color:'#202c3d'},code:{fontSize:16,fontWeight:'600',color:'#286bc0',fontVariant:['tabular-nums']},photos:{flexDirection:'row',gap:8},photo:{width:80,height:80,borderRadius:7,backgroundColor:'#edf2f8'},photoStatus:{fontSize:9,color:'#936622',marginTop:4},row:{flexDirection:'row',gap:14,alignItems:'center',flexWrap:'wrap'},smallAction:{minHeight:34,justifyContent:'center'},link:{fontSize:12,fontWeight:'500',color:'#286bc0'},remove:{color:'#a24337',fontSize:22},required:{fontSize:11,color:'#936622'},noDamage:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:12},check:{fontSize:23,color:'#286bc0'},button:{minHeight:46,alignItems:'center',justifyContent:'center',padding:13,borderRadius:8,backgroundColor:'#286bc0'},buttonText:{fontSize:13,fontWeight:'600',color:'white'},secondary:{backgroundColor:'#f5f8fc',borderWidth:1,borderColor:'#e4eaf1'},secondaryText:{color:'#202c3d'},dim:{opacity:.45},notice:{backgroundColor:'#fff6e7',padding:12,borderRadius:8,gap:8},noticeText:{fontSize:12,lineHeight:18,color:'#856221'}});
