const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {app,loadDriver}=require('./driver-module.cjs');
const React=require(path.join(app,'node_modules/react')),renderer=require(path.join(app,'node_modules/react-test-renderer'));
const {act}=renderer;globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const initial={id:'11111111-1111-4111-8111-111111111111',title:'Load #1042 · Miami',dealerName:'Northline Motors',carrierName:'Sofia Logistics LLC',carrierDot:'6180636',driverName:'John Smith',driverPhone:'+15551234567',status:'pending',vehicles:['2025 BMW X5'],pickupAddress:'Atlanta auction · Atlanta, GA',deliveryAddress:'Northline Motors · Miami, FL',plannedAt:null,expiresAt:new Date(Date.now()+86400000).toISOString(),acceptedAt:null,completedAt:null};
async function mountDriver(ready=true){
 let session={user:{id:'driver',phone:'15551234567'},access_token:'fixture'},record={...initial},current,tree,callback,access={services:true,foreground:true,background:ready,precise:true},permissionFails=false,acceptResponseLost=false,calls=[],started=false;
 const listeners=[];let health={enabled:false,queued:0,lastUpload:null,lastCapture:null,error:null};
 const native={AppState:{currentState:'active',addEventListener:(_,fn)=>{listeners.push(fn);return {remove:()=>listeners.splice(listeners.indexOf(fn),1)}}},Alert:{alert:(_title,_copy,buttons)=>buttons.at(-1).onPress()},Linking:{openSettings:async()=>calls.push('settings')}};
 const auth={getSession:async()=>({data:{session}}),onAuthStateChange:fn=>{callback=fn;return {data:{subscription:{unsubscribe(){}}}}},startAutoRefresh(){},stopAutoRefresh(){},signOut:async()=>{session=null;callback('SIGNED_OUT',null);return {}},signInWithOtp:async()=>({}),verifyOtp:async()=>({})};
 const api={ApiError:class extends Error{},getLoads:async()=>({items:[{...record}],serverNow:new Date().toISOString()}),loadAction:async(id,action)=>{assert.equal(id,record.id);calls.push(action);if(action==='accept'){if(record.status!=='pending')throw new Error('Already accepted');record.status='accepted';if(acceptResponseLost){acceptResponseLost=false;throw new Error('Response lost');}}else if(action==='start'){assert.ok(['accepted','paused','active'].includes(record.status));record.status='active';}else if(action==='pause')record.status='paused';else if(action==='complete')record.status='completed';return {load:{...record}}},pauseAll:async()=>{calls.push('pause-all');record.status='paused'}};
 const tracking={locationAccess:async()=>({...access}),requestLocationPermissions:async()=>{calls.push('permissions');if(permissionFails)throw new Error('Needs Always');access.background=true},syncTracking:async(loads,enable=false)=>{if(enable){started=true;health.enabled=true}else if(!loads.some(v=>v.status==='active'))health.enabled=false},captureIfDue:async()=>{},captureNow:async()=>{calls.push('capture');health.lastCapture=new Date().toISOString();health.lastUpload=health.lastCapture},flushQueue:async()=>{},trackingHealth:async()=>({...health}),stopCollecting:async()=>{health.enabled=false}};
 const {useDriver}=loadDriver('src/useDriver.ts',{'react-native':native,'expo-linking':{useURL:()=>null,parse:()=>({})},'./auth':{supabase:{auth}},'./api':api,'./tracking':tracking});
 function Probe(){current=useDriver();return React.createElement('probe');}
 await act(async()=>{tree=renderer.create(React.createElement(Probe));await new Promise(resolve=>setTimeout(resolve,10));});
 return {get current(){return current},get calls(){return calls},get record(){return record},get started(){return started},setReady:()=>access.background=true,failPermission:()=>permissionFails=true,loseAcceptResponse:()=>acceptResponseLost=true,event:async state=>{native.AppState.currentState=state;await act(async()=>{listeners.forEach(fn=>fn(state));await new Promise(resolve=>setTimeout(resolve,10));})},close:async()=>act(async()=>tree.unmount())};
}
(async()=>{
 let test=await mountDriver();
 try{await act(async()=>test.current.beginStart(test.current.visible[0]));assert.equal(test.record.status,'active');assert.deepEqual(test.calls.filter(v=>['accept','start'].includes(v)),['accept','start']);assert.equal(test.current.permissionOpen,false);assert.equal(test.started,true);console.log('PASS one action accepts and starts with existing permission');}finally{await test.close();}
 test=await mountDriver(false);
 try{await act(async()=>test.current.beginStart(test.current.visible[0]));assert.equal(test.current.permissionOpen,true);assert.equal(test.calls.includes('accept'),false);test.failPermission();await act(async()=>test.current.enableLocation());assert.equal(test.current.permissionStep,'settings');assert.equal(test.record.status,'pending');await act(async()=>test.current.openSettings());await test.event('background');test.setReady();await test.event('active');assert.equal(test.record.status,'active');assert.equal(test.current.permissionOpen,false);assert.deepEqual(test.calls.filter(v=>['accept','start'].includes(v)),['accept','start']);console.log('PASS permission denial, Settings → Always and automatic continuation of the selected load');}finally{await test.close();}
 test=await mountDriver(false);
 try{await act(async()=>test.current.beginStart(test.current.visible[0]));await act(async()=>test.current.closePermission());test.setReady();await test.event('active');assert.equal(test.calls.includes('start'),false);assert.equal(test.record.status,'pending');console.log('PASS closing permission guidance cancels the start intent');}finally{await test.close();}
 test=await mountDriver();
 try{test.loseAcceptResponse();await act(async()=>test.current.beginStart(test.current.visible[0]));assert.equal(test.record.status,'accepted');await act(async()=>test.current.beginStart(test.current.visible[0]));assert.equal(test.record.status,'active');assert.deepEqual(test.calls.filter(v=>['accept','start'].includes(v)),['accept','start']);console.log('PASS retry after a lost acceptance response does not accept twice');}finally{await test.close();}
 test=await mountDriver();
 try{await act(async()=>test.current.act(test.current.visible[0],'accept'));assert.equal(test.record.status,'accepted');assert.equal(test.calls.includes('start'),false);assert.equal(test.started,false);console.log('PASS accept for later preserves the choice to start tracking separately');}finally{await test.close();}
})().catch(error=>{console.error(error);process.exitCode=1});
