const fs = require('node:fs');
const path = require('node:path');
const {groups, articles} = require('./help-content.cjs');
const escape = text => String(text).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths = {compass:'<circle cx="12" cy="12" r="9"/><path d="m16 8-2 6-6 2 2-6Z"/>',shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 12 3 3 5-6"/>',pin:'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/>',phone:'<rect x="6" y="2" width="12" height="20" rx="3"/><path d="M11 18h2"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9 9a3 3 0 0 1 6 0c0 2-3 2-3 5M12 17h.01"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 4 4"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>'};
const icon = name => `<svg viewBox="0 0 24 24" aria-hidden="true">${paths[name] || paths.arrow}</svg>`;
const themeSwitch = '<button class="theme-toggle" type="button" role="switch" aria-label="Light theme" aria-checked="false" data-theme-toggle><span data-theme-label>Dark</span><span class="theme-switch" aria-hidden="true"></span></button>';
const searchButton = (className, label) => `<button class="${className}" type="button" data-search-open>${icon('search')}<span>${label}</span><kbd>⌘ K</kbd></button>`;
const card = article => `<a class="guide-card" href="/help/${article.slug}"><span class="card-top">${icon(groups.find(g => g.id === article.group).icon)}<span>${article.time} min read</span></span><h3>${article.title}</h3><p>${article.description}</p><span class="card-link">Read guide ${icon('arrow')}</span></a>`;
function shell(article, body) {
  const group = article && groups.find(g => g.id === article.group);
  const url = '/help' + (article ? '/' + article.slug : '');
  const nav = groups.map(g => `<section class="nav-group"><h2>${g.title}</h2>${articles.filter(a => a.group === g.id).map(a => `<a href="/help/${a.slug}"${article?.slug === a.slug ? ' aria-current="page"' : ''}>${a.title}</a>`).join('')}</section>`).join('');
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#090b0e"><title>${escape(article ? article.title : 'Help Center')} · DeepTruck</title><meta name="description" content="${escape(article ? article.description : 'Step-by-step DeepTruck guides for carrier verification, documents, load tracking and the Driver app.')}"/><link rel="canonical" href="https://www.deeptruck.io${url}"><meta property="og:title" content="${escape(article ? article.title : 'DeepTruck Help Center')}"><meta property="og:description" content="${escape(article ? article.description : 'Clear guides. Confident deliveries.')}"><meta property="og:url" content="https://www.deeptruck.io${url}"><meta property="og:type" content="${article ? 'article' : 'website'}"><link rel="icon" href="/favicon.svg"><script src="/theme.js"></script><link rel="stylesheet" href="/help/help.css"><script src="/help/help.js" defer></script></head>
<body class="help-page"><a class="skip-link" href="#content">Skip to content</a>
<header class="help-header"><a class="help-brand" href="/help"><img data-theme-logo src="/shield-mark.svg" width="27" height="31" alt=""><strong>DeepTruck</strong><span>Help Center</span></a>${searchButton('header-search','Search guides')}<nav aria-label="Site navigation"><a class="website-link" href="/">Website ↗</a><a class="workspace-link" href="/admin/">Open workspace ${icon('arrow')}</a></nav><button class="menu-toggle" type="button" aria-label="Open guide navigation" aria-expanded="false" aria-controls="guide-nav">☰</button></header>
<div class="help-layout"><aside class="help-sidebar" id="guide-nav"><nav aria-label="Guide navigation"><a class="overview-link" href="/help"${!article ? ' aria-current="page"' : ''}>${icon('compass')} Help overview</a>${nav}</nav><a class="sidebar-support" href="mailto:verify@deeptruck.io">${icon('help')} Contact support ↗</a></aside>
<main id="content" tabindex="-1" class="help-main ${article ? 'article-main' : 'home-main'}">${body}<footer class="help-footer"><a href="/">DeepTruck</a><a href="/privacy">Privacy</a>${themeSwitch}</footer></main>
${article ? `<aside class="contents-rail"><nav aria-label="On this page"><h2>On this page</h2>${article.sections.map(s => `<a href="#${s.id}">${s.title}</a>`).join('')}</nav><div class="rail-support"><strong>Need a hand?</strong><p>We’re here to help.</p><a href="mailto:verify@deeptruck.io?subject=${encodeURIComponent(article.title)}">Contact support ↗</a></div></aside>` : ''}</div>
<dialog id="search-dialog" aria-labelledby="search-title"><div class="search-dialog-top"><h2 id="search-title">Search Help Center</h2><button type="button" class="dialog-close" data-search-close aria-label="Close search">×</button></div><label class="search-input-wrap">${icon('search')}<input id="guide-search" type="search" aria-label="Search guides" placeholder="Try “Always”, “invite” or “documents”" autocomplete="off"></label><div id="search-status" class="search-status" role="status" aria-live="polite"></div><div id="search-results"></div><div class="search-dialog-footer"><span>↑ ↓ to navigate · Enter to open</span><span>Esc to close</span></div></dialog>
<dialog id="image-dialog" aria-label="Guide screenshot"><button type="button" class="dialog-close" data-image-close aria-label="Close screenshot">×</button><img id="zoom-image" alt=""></dialog>
</body></html>`;
}
module.exports = function buildHelp(output) {
  const help = path.join(output, 'help');
  fs.mkdirSync(help, {recursive:true});
  const lead = `<div class="home-intro"><span class="eyebrow">DEEPTRUCK GUIDES</span><h1>Clear guides.<br><span>Confident deliveries.</span></h1><p>Everything you need to verify carriers, track loads<br class="desktop-break"> and get drivers on the road.</p>${searchButton('home-search','What would you like to do?')}</div>
<div class="role-guides"><a href="/help/getting-started"><span class="role-icon">${icon('shield')}</span><div><span class="eyebrow">FOR DISPATCHERS</span><h2>From carrier check to delivery</h2><p>Start with the complete workspace walkthrough.</p></div>${icon('arrow')}</a><a href="/help/accept-load"><span class="role-icon">${icon('phone')}</span><div><span class="eyebrow">FOR DRIVERS</span><h2>Your load. Ready to go.</h2><p>Sign in, accept a load and set up location.</p></div>${icon('arrow')}</a></div>
<section class="home-section"><div class="section-heading"><h2>Start here</h2><span>Popular guides</span></div><div class="guide-cards">${['verify-carrier','create-tracking','location-permissions'].map(slug => card(articles.find(a => a.slug === slug))).join('')}</div></section>
<section class="home-section browse-section"><div class="section-heading"><h2>Explore the guides</h2><span>Find your next step</span></div><div class="browse-groups">${groups.map(g => `<section><h3>${icon(g.icon)}${g.title}</h3>${articles.filter(a => a.group === g.id).map(a => `<a href="/help/${a.slug}">${a.title}${icon('arrow')}</a>`).join('')}</section>`).join('')}</div></section>
<aside class="home-support">${icon('help')}<div><h2>Something not working?</h2><p>Check the ${'<a href="/help/troubleshooting">quick troubleshooting guide</a>'} or reach out to our team.</p></div><a href="mailto:verify@deeptruck.io">Contact support ↗</a></aside>`;
  fs.writeFileSync(path.join(help, 'index.html'), shell(null, lead));
  for (const article of articles) {
    const group = groups.find(g => g.id === article.group);
    const siblings = articles.filter(a => a.group === article.group);
    const related = siblings.filter(a => a !== article).slice(0,2);
    const body = `<div class="breadcrumbs"><a href="/help">Help Center</a><span aria-hidden="true">/</span><span>${group.title}</span></div><article><header class="article-heading"><div class="article-meta"><span>${article.audience}</span><span>·</span><span>${article.time} min read</span></div><h1>${article.title}</h1><p>${article.description}</p><div class="article-tools"><button type="button" id="copy-guide">Copy guide link ${icon('arrow')}</button><button type="button" id="print-guide">Print guide</button><span id="copy-status" role="status"></span></div></header><details class="mobile-contents"><summary>On this page</summary><nav>${article.sections.map(s => `<a href="#${s.id}">${s.title}</a>`).join('')}</nav></details>${article.sections.map(s => `<section class="article-section" aria-labelledby="${s.id}"><h2 id="${s.id}">${s.title}<a href="#${s.id}" class="heading-anchor" aria-label="Link to ${s.title}">#</a></h2>${s.html}</section>`).join('')}</article><div class="article-end"><p>Still have a question? <a href="mailto:verify@deeptruck.io?subject=${encodeURIComponent(article.title)}">Contact support ↗</a></p><span>Guides follow the current DeepTruck interface.</span></div>${related.length ? `<section class="related-guides"><h2>Keep going</h2><div>${related.map(a => `<a href="/help/${a.slug}"><span>${a.title}</span>${icon('arrow')}</a>`).join('')}</div></section>` : ''}`;
    // Flat .html files work with Vercel cleanUrls and direct reloads.
    fs.writeFileSync(path.join(help, article.slug+'.html'), shell(article, body));
  }
  const index = articles.map(a => ({title:a.title,description:a.description,url:'/help/'+a.slug,group:groups.find(g => g.id === a.group).title,text:a.sections.map(s => s.title+' '+s.html.replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&')).join(' ')}));
  fs.writeFileSync(path.join(help,'search-index.json'),JSON.stringify(index));
  fs.writeFileSync(path.join(output,'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['/','/help',...articles.map(a => '/help/'+a.slug),'/privacy','/terms'].map(url => `<url><loc>https://www.deeptruck.io${url}</loc></url>`).join('')}</urlset>`);
};
